spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha-ordercenter?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: 795138462
      minimum-idle: 10
      maximum-pool-size: 20
      max-lifetime: 180000
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 10
        max-active: 20
    database: 0
  application:
    name: order-center
  cloud:
    nacos:
      server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:9090     #指定sentinel控制台地址
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
#    add-mappings: false
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true    #驼峰命名



mq.nameserver.addr: 39.97.231.163:9876
mq.topicname: stock
feign:
  client:
    config:
      default:
        loggerLeavel: basic
  httpclient:
    enabled: true                   #让feign使用Apache 的HTTPClient, 可以使用连接池优化性能
    max-connections: 50             #连接池最大连接数
    max-connections-per-route: 10   #单个feignClient最大连接数
management:
  endpoints:
    web:
      exposure:
        include: '*'